# Generated by Django 6.0.7 on 2026-09-12 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0011_iconblob_installedapp_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField()),
                ('summary', models.TextField()),
                ('highlights', models.JSONField(default=list)),
                ('recommendations', models.JSONField(default=list)),
                ('risk_level', models.CharField(choices=[('ok', 'Yaxshi'), ('watch', 'Kuzatish kerak'), ('concern', 'Tashvishli')], default='ok', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_insights', to='devices.child')),
            ],
            options={
                'ordering': ['-week_start'],
                'unique_together': {('child', 'week_start')},
            },
        ),
    ]
