# Generated by Django 6.0.7 on 2026-09-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_iconblob_installedapp_icon'),
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyinsight',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='weeklyinsight',
            name='period',
            field=models.CharField(choices=[('last_week', "O'tgan hafta"), ('this_week', 'Shu hafta'), ('today', 'Bugun')], default='last_week', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='weeklyinsight',
            unique_together={('child', 'period', 'week_start')},
        ),
    ]
