# Generated by Django 6.0.7 on 2026-07-28 04:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0002_childdevice_last_sync'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('limit_reached', 'limit_reached'), ('blocked_app_opened', 'blocked_app_opened')], max_length=30)),
                ('payload', models.JSONField()),
                ('triggered_at', models.DateTimeField()),
                ('seen', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='devices.childdevice')),
            ],
        ),
    ]
