# Generated by Django 6.0.7 on 2026-09-01 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_type',
            field=models.CharField(choices=[('limit_reached', 'limit_reached'), ('blocked_app_opened', 'blocked_app_opened'), ('settings_panel_access', 'settings_panel_access')], max_length=30),
        ),
    ]
