# Generated by Django 6.0.7 on 2026-07-28 03:03

import django.db.models.deletion
import secrets
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_name', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('unlinked', 'Unlinked'), ('linked', 'Linked')], default='unlinked', max_length=20)),
                ('device_secret', models.CharField(default=secrets.token_hex, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('linked_at', models.DateTimeField(blank=True, null=True)),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='accounts.family')),
            ],
        ),
        migrations.CreateModel(
            name='EnrollmentCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('qr_payload', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='devices.childdevice')),
            ],
        ),
    ]
