# Generated by Django 6.0.7 on 2026-07-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='last_sync',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
