# Generated by Django 6.0.7 on 2026-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_child_photo_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='agent_version',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
