# Generated by Django 6.0.7 on 2026-09-01 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_childdevice_agent_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='hardware_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
