# Generated by Django 6.0.7 on 2026-09-12 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_childdevice_hardware_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='geo_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childdevice',
            name='geo_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childdevice',
            name='geo_location_label',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='childdevice',
            name='geo_source',
            field=models.CharField(blank=True, choices=[('ip', 'IP'), ('gps', 'GPS')], max_length=8),
        ),
        migrations.AddField(
            model_name='childdevice',
            name='geo_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='childdevice',
            name='last_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='InstalledApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(blank=True, max_length=100)),
                ('publisher', models.CharField(blank=True, max_length=200)),
                ('install_date', models.DateField(blank=True, null=True)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='installed_apps', to='devices.childdevice')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('device', 'name')},
            },
        ),
    ]
