# Generated by Django 6.0.7 on 2026-09-12 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_childdevice_geo_lat_childdevice_geo_lng_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='installedapp',
            name='uninstalled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
