# Generated by Django 6.0.7 on 2026-09-14 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_iconblob_installedapp_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='childdevice',
            name='account_is_admin',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
