# Generated by Django 6.0.7 on 2026-08-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_parentuser_full_name_parentuser_telegram_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlogintoken',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
