# Generated by Django 6.0.7 on 2026-09-01 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramlogintoken_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramlogintoken',
            name='is_link',
            field=models.BooleanField(default=False),
        ),
    ]
