# Generated by Django 6.0.7 on 2026-09-10 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='last_onboarding_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='onboarding_reminders_sent',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='onboarding_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('beta', 'Beta (bepul)')], default='beta', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('canceled', 'Canceled')], default='active', max_length=12)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('renews_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider', models.CharField(blank=True, default='', max_length=30)),
                ('provider_ref', models.CharField(blank=True, default='', max_length=120)),
                ('family', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='accounts.family')),
            ],
        ),
    ]
