# Generated by Django 6.0.7 on 2026-09-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_flag_existing_for_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('beta', 'Beta (bepul)'), ('mini', 'Mini'), ('max', 'Max')], default='beta', max_length=20),
        ),
    ]
