# Generated by Django 6.0.7 on 2026-09-12 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_subscription_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('beta', 'Beta (bepul)'), ('mini', 'Mini'), ('max', 'Max'), ('tester', 'Tester (cheksiz, faqat sinovchilar uchun)')], default='beta', max_length=20),
        ),
    ]
