# Generated by Django 6.0.7 on 2026-09-13 19:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_subscription_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='instagram_username',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='parentuser',
            name='referred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('beta', 'Beta (7 kunlik sinov)'), ('mini', 'Mini'), ('max', 'Max'), ('tester', 'Tester (cheksiz, faqat sinovchilar uchun)')], default='beta', max_length=20),
        ),
    ]
