# Generated by Django 6.0.7 on 2026-09-13 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_parentuser_instagram_username_parentuser_referred_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentuser',
            name='awaiting_telegram_story_proof',
            field=models.BooleanField(default=False),
        ),
    ]
