# Generated by Django 6.0.7 on 2026-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_parentuser_awaiting_telegram_story_proof'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentuser',
            name='awaiting_telegram_story_proof',
        ),
        migrations.RemoveField(
            model_name='parentuser',
            name='instagram_username',
        ),
        migrations.AddField(
            model_name='parentuser',
            name='awaiting_story_proof_for',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
