# Generated by Django 6.0.7 on 2026-09-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_parentuser_awaiting_telegram_story_proof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parentuser',
            name='awaiting_story_proof_for',
        ),
    ]
