# Generated by Django 6.0.7 on 2026-09-13 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_seed_default_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='target_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
