# Generated by Django 6.0.7 on 2026-09-13 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_configure_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskcompletion',
            name='proof_file_id',
        ),
    ]
