# Generated by Django 6.0.7 on 2026-09-10 05:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0008_childdevice_hardware_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotCleanupRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('expired_count', models.PositiveIntegerField(default=0)),
                ('unclaimed_count', models.PositiveIntegerField(default=0)),
                ('objects_deleted', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ScreenshotRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('retention', models.CharField(choices=[('day', '1 kun'), ('week', '1 hafta'), ('month', '1 oy')], default='week', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('capturing', 'Olinmoqda'), ('uploaded', 'Tayyor'), ('failed', 'Xatolik'), ('expired', 'Muddati tugagan')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('captured_at', models.DateTimeField(blank=True, null=True)),
                ('error', models.CharField(blank=True, max_length=300)),
                ('r2_key', models.CharField(blank=True, max_length=200)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('size_bytes', models.PositiveIntegerField(blank=True, null=True)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_requests', to='devices.childdevice')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='screenshot_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'status'], name='shot_device_status_idx')],
            },
        ),
    ]
