# Generated by Django 6.0.7 on 2026-08-29 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deploy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentversion',
            options={'ordering': ['-released_at']},
        ),
        migrations.AddField(
            model_name='agentversion',
            name='mandatory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agentversion',
            name='sha256',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='agentversion',
            name='signature',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='agentversion',
            name='binary_url',
            field=models.URLField(max_length=500),
        ),
    ]
