# Generated by Django 6.0.7 on 2026-08-29 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0006_child_photo_nullable'),
        ('tracking', '0002_event_query_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceAppIcon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.CharField(max_length=200)),
                ('sha256', models.CharField(max_length=64)),
                ('data_b64', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='app_icons', to='devices.childdevice')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('device', 'app_id'), name='uniq_device_app_icon')],
            },
        ),
    ]
