# Generated by Django 6.0.7 on 2026-09-12 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0011_iconblob_installedapp_icon'),
        ('tracking', '0006_backfill_icon_blobs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceappicon',
            name='data_b64',
        ),
        migrations.RemoveField(
            model_name='deviceappicon',
            name='sha256',
        ),
        migrations.AlterField(
            model_name='deviceappicon',
            name='icon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='devices.iconblob'),
            preserve_default=False,
        ),
    ]
