# Generated by Django 6.0.7 on 2026-09-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rule_rule_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rule',
            name='rule_type',
            field=models.CharField(choices=[('daily_limit_minutes', 'daily_limit_minutes'), ('app_daily_limit_minutes', 'app_daily_limit_minutes'), ('blocked_app', 'blocked_app'), ('blocked_window', 'blocked_window')], max_length=30),
        ),
    ]
